[phases.setup]
nixPkgs = ['...', 'jdk']

[phases.build]
cmds = [
    'cd backend && chmod +x mvnw && ./mvnw clean package -DskipTests'
]

[start]
cmd = 'java -Dserver.port=$PORT -jar backend/target/service-status-backend-0.0.1-SNAPSHOT.jar'
