[phases.setup]
nixPkgs = ["...", "jdk21"]

[phases.build]
cmds = ["cd backend && ./mvnw clean package -DskipTests"]

[phases.start]
cmd = "cd backend && java -Dserver.port=$PORT -jar target/service-status-backend-0.0.1-SNAPSHOT.jar"
