name: full-stack-ci

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  frontend:
    runs-on: ubuntu-latest 
    
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      
      - name: Setup Node.js with multiple versions
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      

      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npx vitest run --coverage
      
      - name: Build project
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.BACKEND_URL || 'https://YOUR_BACKEND_URL_HERE' }} 

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/
          retention-days: 7 
        
  
  backend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21 
          distribution: 'temurin' 
          cache: 'maven'
      
      - name: Run tests
        run: ./mvnw test
        env:
          SPRING_PROFILES_ACTIVE: test  
      
      - name: Build project
        run:  ./mvnw clean package 
      
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar  
          retention-days: 7     
  
  deploy:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only on main branch
    
    permissions:
      contents: write  # Required for GitHub Pages deployment
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./dist
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: false  # Set to your custom domain if you have one
      
      - name: Backend Deployment Reminder
        run: |
          echo "✅ Frontend deployed to GitHub Pages"
          echo "⚠️  Backend deployment required:"
          echo "    1. Go to Render dashboard: https://dashboard.render.com/"
          echo "    2. Select service-status-backend"
          echo "    3. Click 'Manual Deploy' > 'Deploy latest commit'"
          echo "    4. Add BACKEND_URL secret to GitHub if not already done"
          echo "       Settings > Secrets > Actions > New repository secret"
          echo "       Name: BACKEND_URL, Value: https://your-app.onrender.com"